### ISSUE TITLE
Headers and images too large on mobile

### ISSUE THREAD

**Issue by cjmlgrto** [RamonGilabert/UIWebsiteKit#1]
The website needs to scale down and the paddings need to be smaller for screen sizes smaller than 500px— otherwise the headers look way too huge and the some icons are cropped due to the size.

**Comment by RamonGilabert** [comment]
On it tomorrow morning, did a bit of progress for the header, but wanna change the table to be something different. I'll keep you posted.

Also, when we push this version of the site I'll change the organization name to `puzzles-design`. :)

**Here's the current status (iPhone 4S):**

<img width="362" alt="screen shot 2016-06-17 at 11 20 03 pm" src="https://cloud.githubusercontent.com/assets/6138120/16165062/0c15959a-34e2-11e6-9948-6e31edabca20.png">
